# SPDX-PackageName: finnix-docs
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://github.com/rfinnie/finnix-docs
# SPDX-FileCopyrightText: Â© 2023 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MPL-2.0
---
fail_fast: false

repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v6.0.0"
    hooks:
      - id: "check-added-large-files"
      - id: "check-case-conflict"
      - id: "check-executables-have-shebangs"
      - id: "check-xml"
      - id: "check-yaml"
        args:
          - "--unsafe"
      - id: "check-json"
      - id: "check-shebang-scripts-are-executable"
      - id: "detect-private-key"
      - id: "end-of-file-fixer"
      - id: "fix-byte-order-marker"
      - id: "requirements-txt-fixer"
      - id: "trailing-whitespace"

  - repo: "https://github.com/adrienverge/yamllint"
    rev: "v1.38.0"
    hooks:
      - id: "yamllint"
        args:
          - "-c"
          - ".yamllint.yml"

  - repo: "https://github.com/psf/black"
    rev: "26.1.0"
    hooks:
      - id: "black"

  - repo: "https://github.com/pycqa/flake8"
    rev: "7.3.0"
    hooks:
      - id: "flake8"

  - repo: "https://github.com/rhysd/actionlint"
    rev: "v1.7.11"
    hooks:
      - id: "actionlint"

  - repo: "https://codeberg.org/fsfe/reuse-tool"
    rev: "v6.2.0"
    hooks:
      - id: "reuse"
